/**
 * The SDK variable catalogue: what the simulator has, independent of anyone.
 *
 * Every other source of variable knowledge in this app is *discovered* — the
 * corpus is what somebody wrote into a profile, the enumeration is what this
 * machine's sim reported, an observation is what moved during a flight. All of
 * it accumulates in the database and is true about one install.
 *
 * This is the opposite: it is **shipped**, generated at development time from
 * the MSFS SDK and committed. That is why it is a file and not a table — the
 * database holds what a machine learned, and a catalogue baked into the binary
 * that also lived in the database could disagree with itself across an upgrade,
 * with no honest way to say which won.
 *
 * Generated by `scripts/build-sdk-var-catalog.ts`; never edited by hand.
 *
 * ## Two sources, kept apart
 *
 * The catalogue has the same problem one level down that the variable index has
 * one level up, and it takes the same answer. Asobo's model-behaviour templates
 * say which variables are *used*; the SDK documentation says which exist and
 * what they mean. They disagree in both directions — a variable can be worked
 * hard by the templates and undocumented, or documented and never touched — and
 * flattening them into one set of fields would throw away exactly the
 * distinction that makes an undocumented-but-used variable interesting.
 *
 * So observation and declaration travel separately: `usedUnits` is what the
 * templates do, `doc.units` is what the SDK says, and `from` records which
 * sources have seen this name at all.
 */

/** Which generator pass contributed to an entry. */
export type SdkVarSource = "templates" | "docs"

/** What the SDK documentation says about one variable. */
export interface SdkVarDoc {
  /** Prose, tags stripped. The docs' own wording, not a summary of it. */
  description: string
  /**
   * The documented unit, as a bare name — `Bool`, `Percent`, `Rpm`.
   *
   * Where the docs spell out an enumeration or add a note, the unit is the
   * first line of the cell and the rest is kept in `unitsDetail`. Splitting it
   * is what keeps this field joinable against `UNITS` and against the units a
   * profile writes, which is the only thing anything needs it for.
   */
  units?: string
  /** The remainder of a units cell that said more than a unit — enum values. */
  unitsDetail?: string
  /**
   * Whether the SDK marks it writable.
   *
   * Worth carrying for a reason specific to this app: an FSC profile drives the
   * cockpit through `set:`, so "can this be written" is the difference between
   * a usable candidate and a dead end. Undefined where the docs said neither.
   */
  settable?: boolean
  /**
   * What the variable's index *means* — `Engine Index`, `Generic Index`.
   *
   * Not a flag. `A:GENERAL ENG RPM:1` is engine one, and the docs are the only
   * place that says so.
   */
  index?: string
  /**
   * Arguments the variable takes, where the docs give it a `Parameters` column
   * instead of an `Index` one. A different idea from an index and kept as one:
   * three of the ninety-odd tables use it.
   */
  parameters?: string
  /**
   * The SimConnect name of a key event — `KEY_AP_AIRSPEED_HOLD` for `K:`
   * `AP_AIRSPEED_HOLD`. Two names for one event: RPN fires it by the short one
   * and a SimConnect client by this one, and only the documentation pairs them.
   */
  eventId?: string
  /** The documentation page it came from — `Aircraft Engine Variables`. */
  category?: string
  /**
   * The docs lead a retired variable's description with "Deprecated", which is
   * prose rather than markup, so this is read from the wording. Conservative on
   * purpose: it marks only what announces itself.
   */
  deprecated?: boolean
}

/** One variable the SDK knows about. */
export interface SdkVar {
  /** Namespaced and un-indexed — `A:GENERAL ENG RPM`, not `…:1`. */
  name: string
  /** Which passes found it. A name in only one of them is a fact worth having. */
  from: SdkVarSource[]
  /**
   * Units the templates were seen reading it in, most-used first.
   *
   * A set rather than a unit: the same variable is legitimately read several
   * ways, and which ways is a fact about the variable.
   */
  usedUnits?: string[]
  /**
   * How many times Asobo's templates reference it.
   *
   * The ranking signal for entries with no other evidence. A catalogue is
   * mostly names nobody in this workspace has ever written, and without this
   * they would sort against each other arbitrarily; a variable the SDK's own
   * templates touch forty times is not the same candidate as one touched once.
   */
  uses?: number
  /** Absent until the docs pass has seen it. */
  doc?: SdkVarDoc
}

/** Where one pass got its data, and how much of it there was. */
export interface SdkCatalogSource {
  id: SdkVarSource
  /** Enough to reproduce the pass: an SDK version, or a docs edition. */
  origin: string
  /** When it was read, as an ISO date. */
  read: string
  /** How many distinct names it contributed. */
  vars: number
}

export interface SdkVarCatalog {
  /** Bumped only by a breaking change to this shape. */
  schema: 1
  generated: string
  sources: SdkCatalogSource[]
  /** Sorted by name, so the committed file diffs meaningfully. */
  vars: SdkVar[]
}
