/**
 * Rebuilds `src/main/sim/fixtures/link-session.ndjson`.
 *
 * The fixture is synthetic and says so. It exists because the module's own
 * output cannot be captured until somebody starts MSFS with it installed, and
 * `L:` live values should not have to wait for that to be developed.
 *
 * It is generated by a script rather than written by hand for one reason: the
 * previous hand-written version claimed in its README to use real `L:` names
 * from `pa24-250.yaml`, and **four of its five names did not exist** — so the
 * one fixture built to exercise `L:` hints could light a single line out of
 * 295. Reading the names out of the profile makes that class of mistake
 * impossible rather than merely unlikely.
 *
 *   node --experimental-strip-types scripts/make-link-fixture.ts
 *
 * Delete this script when a real capture replaces the fixture.
 */

import { readFileSync, writeFileSync } from "node:fs"
import { homedir } from "node:os"
import { join } from "node:path"

import { scanLines, splitUnits } from "../src/shared/profile/index.ts"
import type { CapturedEvent } from "../src/shared/sim.ts"

const PROFILE =
  process.env.FSCE_PROFILE ??
  join(homedir(), "dev/fscopilot/bin/FSCopilot/Definitions/pa24-250.yaml")

const OUT = join(
  import.meta.dirname,
  "..",
  "src",
  "main",
  "sim",
  "fixtures",
  "link-session.ndjson"
)

/** Every `L:` a `get:` line in the profile asks for, in file order. */
function lvarsIn(text: string): { name: string; units: string }[] {
  const seen = new Map<string, string>()

  for (const line of scanLines(text)) {
    if (line.kind !== "entry" || line.key !== "get") continue

    const { name, units } = splitUnits(line.value)
    if (!name.startsWith("L:") || seen.has(name)) continue

    seen.set(name, units)
  }

  return [...seen].map(([name, units]) => ({ name, units }))
}

/**
 * A plausible value for a variable, from its name.
 *
 * Switches and buttons read as 0/1 and everything else ramps. The point is not
 * fidelity — a real capture will replace this — it is that a hint should be
 * recognisable as the right *kind* of number while the path is being built.
 */
function shape(name: string): "toggle" | "ramp" {
  return /switch|button|knob$|lever|selector|breaker|light|pump|master/i.test(name)
    ? "toggle"
    : "ramp"
}

const profile = readFileSync(PROFILE, "utf8")
const lvars = lvarsIn(profile)
if (!lvars.length) throw new Error(`no L: get: lines in ${PROFILE}`)

const t0 = Date.UTC(2026, 7, 23, 12, 0, 0)
const events: CapturedEvent[] = []

const at = (offset: number, event: object): void => {
  events.push({ t: t0 + offset, via: "link", ...event } as CapturedEvent)
}

// The client's half. `via: "client"` because these come from SimConnect, not
// from the module — a capture that got this wrong would teach the Log panel's
// filters something untrue.
events.push({
  t: t0,
  via: "client",
  kind: "open",
  protocol: "SunRise",
  app: "SunRise",
  appVersion: "12.2",
  simConnectVersion: "11.0",
})
events.push({
  t: t0 + 500,
  via: "client",
  kind: "aircraft",
  key: "pa24-250",
  path: "SimObjects/Airplanes/pa24-250/aircraft.cfg",
})

// The module. A hello carrying the count, then the enumeration, then deltas.
at(1_000, { kind: "link", version: "0.1.0", protocol: 1, variables: lvars.length })

// Chunked the way the wire chunks it — 8 KB per message — so a reader that
// assumes one `vars` event holds everything is caught here rather than live.
const CHUNK = 120
for (let from = 0; from < lvars.length; from += CHUNK) {
  at(1_100 + (from / CHUNK) * 50, {
    kind: "vars",
    from,
    names: lvars.slice(from, from + CHUNK).map((entry) => entry.name),
  })
}

/*
 * The first tick reports everything, and that is not an embellishment.
 *
 * The module seeds its `last` array with NaN precisely so the first comparison
 * after enumeration is false for every variable — otherwise an app connecting
 * mid-flight would see only what happened to move afterwards. A fixture without
 * that property would let a regression in the app's "keep every value" rule
 * pass unnoticed.
 */
const START = 2_000
lvars.forEach((entry, index) => {
  at(START + index, {
    kind: "var",
    name: entry.name,
    value: shape(entry.name) === "toggle" ? 0 : Number((index % 17).toFixed(4)),
  })
})

/*
 * Then twenty seconds of deltas at 15 Hz, which is what the module actually
 * sends — only what moved. A handful per tick, not the whole table.
 */
const HZ = 15
const SECONDS = 20
let seq = 0

for (let tick = 1; tick <= HZ * SECONDS; tick += 1) {
  const when = START + 200 + Math.round((tick * 1000) / HZ)

  for (let n = 0; n < 3; n += 1) {
    const entry = lvars[(seq * 7 + n * 53) % lvars.length]!
    seq += 1

    at(when, {
      kind: "var",
      name: entry.name,
      value:
        shape(entry.name) === "toggle"
          ? (Math.floor(tick / 15) + n) % 2
          : Number((((tick * 0.37 + n * 3.1) % 30) + 0.5).toFixed(4)),
    })
  }
}

events.push({
  t: t0 + START + 200 + SECONDS * 1000 + 500,
  via: "client",
  kind: "closed",
  reason: "sim quit",
})

writeFileSync(OUT, events.map((event) => JSON.stringify(event)).join("\n") + "\n")

console.log(
  `${OUT}\n  ${events.length} events, ${lvars.length} L: variables from ${PROFILE}`
)
